name: Call reusable MediaWiki tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-mediawiki-tests-workflow:
    uses: miraheze/.github/.github/workflows/mediawiki-tests.yml@master
    strategy:
      matrix:
        include:
          # Latest MediaWiki stable - PHP 8.1
          - mw: 'REL1_43'
            php: 8.1
            php-docker: 81
            composer-test: true
            experimental: false

          # Latest MediaWiki master - PHP 8.1
          - mw: 'master'
            php: 8.1
            php-docker: 81
            composer-test: false
            experimental: true

    with:
      mw: ${{ matrix.mw }}
      php: ${{ matrix.php }}
      php-docker: ${{ matrix.php-docker }}
      experimental: ${{ matrix.experimental }}
      composer-test: ${{ matrix.composer-test }}

    secrets: inherit
